### ISSUE TITLE
Why Restful Services use EF Core and EF 6.x?

### ISSUE THREAD

**Issue by osperezl3** [SyncfusionExamples/blazor-scheduler-crud#4]
Thank you for share us this example, its let me understand different topics.

I have a couple of questions about the Restful_Services project:
1. This project is target to Framework 4.6, any specific reason to use it instead of ASPNet Core?
2. Checking the NUget packages, there are a lot, but you are making reference to EF6 and EF Core in the same project,  is possible to run both in the same project? , is really necessary all this packages?
3. Blazor project is Server Based, can I use the EF entities directly without use Odata?

Thank you

OSCAR

**Comment by maheshtps** [comment]
Hi @osperezl3 ,

sample upgraded using the dotnet core version.
